name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    # Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    # Install Poetry
    - name: Install Poetry
      run: curl -sSL https://install.python-poetry.org | python3 -

    # Install dependencies
    - name: Install dependencies
      run: |
        poetry install

    # Deploy to GitHub Pages
    - name: Deploy with GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./src
        force_orphan: true
        keep_history: false
